# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89d04521fbed20f9c5662f6906100669d01eda19a21560478063a055b5fdf314f784b3d2ba3f286d8e24515061f94af9e51eb3380fc4f6b11038c3cf405d7b68

test:
  secret_key_base: a9b3519eb51b5565458278b6e57bec3a73d5559e5c62706672480a2bde7307add8f1d7f8f1a05f7897f0ff0ad91902592fe0f17d530996504e014cc44f18e740

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
